
## Deskripsi
Berikut adalah repositori yang digunakan untuk menyimpan semua materi untuk **Workshop Multigroup Structural Equation Modeling (MG-SEM)** yang diselenggarakan oleh Departemen Psikologi Kepribadian dan Sosial, Fakultas Psikologi Universitas Airlangga dalam rangka memperingati Dies Natalis Pendidikan Psikologi Universitas Airlangga yang ke-36. 

Materi berlisensi [<i class="fab fa-creative-commons"></i> 4.0](https://creativecommons.org/licenses/by/4.0/). **Materi bebas digunakan kembali namun wajib menyebutkan sumber aslinya**.

## Waktu dan tempat
*Workshop* diselenggarakan pada hari **Jumat-Sabtu, 22-23 November 2019**, pukul 09.00-16.00 WIB di Ruang Sidang I, Fakultas Psikologi Universitas Airlangga.

## *Outline* materi


Berikut adalah *outline* materi *workshop*:

### **Hari 1**
#### Jumat, 22 November 2019


### **Hari 2**
#### Sabtu, 23 November 2019


## Referensi



## Contoh penelitian dengan `MG-SEM`


## Sumber belajar lainnya
* [Learning Statistics with JASP]()


## Sebelum mulai workshop
* Sebaiknya semua peserta sudah memasang JASP pada perangkatnya masing-masing, untuk menghindari terlalu banyaknya waktu untuk menyelesaikan *troubleshooting* instalasi ketika *workshop*.
* Peserta sangat disarankan untuk menonton [video tutorial JASP]() sebelum *workshop* untuk belajar menavigasikan menu dan fitur yang ada dalam jamovi. Cukup hanya dengan menonton yang bagian *Welcome*, *Installing jamovi*, dan *Navigating jamovi* (total durasi kurang lebih hanya 7 menit).


## Video rekaman

### Sesi 1 (08.00-12.00)

[Klik disini untuk menonton video.](https://www.youtube.com/WwlILOtniBw)

### Sesi 2 (13.00-16.00)

[Klik disini untuk menonton video.](https://www.youtube.com/N2O48MoMddQ)


## Pembaruan dan koreksi


## Poster kegiatan


## Jawaban Latihan

### Latihan Mandiri (1): 

[Klik disini untuk melihat jawaban]() saya atas latihan mandiri (1).


### Latihan Mandiri (2):

[Klik disini untuk melihat jawaban]() saya atas latihan mandiri (1).