---
title: "Multigroup Structural Equation Modeling"
---

::: {.callout-note}
### Kuis _Pre-test_
`lme` merupakan teknik statistik yang kompleks dan menguasainya perlu melewati _learning curve_ yang lumayan curam. Agar _workshop_ ini bermanfaat, peserta ***wajib*** untuk mengikuti kuis _pre-test_ sebelum _workshop_ untuk mengetahui apa saja materi yang perlu dipersiapkan sebelum _workshop_ dimulai.

Silakan klik _navigation bar_ `Kuis _Pre-Test_`untuk mengikuti kuis. 
:::

::: {.callout-warning}
#### Perhatian 
Materi akan terus diperbarui sampai dengan H-1 _workshop_.
:::

Laman web berikut ini merupakan laman web untuk **Workshop Multigroup Structural Equation Modeling** yang diselenggarakan oleh program studi Doktor (S3) Psikologi, Fakultas Psikologi, Universitas Airlangga.

Materi berlisensi [<i class="fab fa-creative-commons"><i class="fa fa-universal-access"></i></i> BY 4.0](https://creativecommons.org/licenses/by/4.0/). **Materi bebas digunakan kembali namun wajib mengatribusi sumber aslinya**.

## Waktu dan tempat

*Workshop* diselenggarakan pada hari **Kamis dan Jumat, 7-8 Mei 2026** pukul 15.00 - 17.00 WIB secara virtual melalui Microsoft Teams.

::: {.callout-note}
**Catatan**: Peserta dapat _join meeting_ melalui _browser_, sehingga **tidak harus** _login_ atau memiliki akun MS Teams. 
Namun, apabila peserta ingin menyimpan atau mengakses _history chat_ setelah _workshop_ berakhir, peserta disarankan untuk _login_ akun Microsoft yang disediakan Universitas Airlangga (email dengan domain `@drive.unair.ac.id`) sebelum _join meeting_.
:::

:::{style="text-align: center;"}
[**Klik disini untuk _join meeting_**](https://teams.microsoft.com/meet/48621148240860?p=tnmFEem9q42zVoQqVO)
:::

## *Outline* materi

### Bagian 1️⃣: Pengantar
* Apa itu *structural equation modeling* (SEM)?
* Mengapa dan pada kondisi seperti apa SEM diperlukan?
* Beberapa pilihan perangkat lunak untuk mengeksekusi SEM
* SEM atau PLS?
* Yang tidak dicakup dalam *workshop* serta keterbatasan jamovi

### Bagian 2️⃣: Korelasi
* Jenis-jenis koefisien korelasi
* Faktor-faktor yang membuat koefisien korelasi bervariasi
* [Koreksi atenuasi](https://methods.sagepub.com/reference/encyc-of-research-design/n81.xml) dan *measurement error*
* *Variance-covariance* dan *correlation matrix*
* *WARNING! Covariance/correlation matrix is not positive definite*
* [*Heywood* dan *Ultra-Heywood case*](https://journals.sagepub.com/doi/10.1177/0049124112442138)
* Bivariat, *part*, dan *partial correlation*
* Metrik variabel (*standardized* vs *unstandardized*)

::: {.callout-important}
#### Materi korelasi tidak diajarkan
Karena keterbatasan waktu, bagian **Korelasi** **_tidak diajarkan_** di _workshop_, tetapi **harus dikuasai** oleh peserta terlebih dahulu sebelum memulai _workshop_. Materi ini (seharusnya) sudah diberikan di MK Psikometri/Pengukuran Psikolog/Statistik Dasar di jenjang S1, sehingga asumsinya peserta sudah familiar dengan materi ini. Materi tersedia di laman web ini dan dapat dipelajari secara mandiri.
:::

### Bagian 3️⃣: Model Jalur (*Path Model*) dan Model Regresi
* Definisi *path model*
* Nama variabel dan koefisien jalur (*path coefficients*)
  * δ (delta), ε (epsilon), ξ (ksi), η (eta), λ (lambda), γ (gamma), β (beta), φ (phi), ζ (zeta)
* Representasi visual model jalur menggunakan diagram jalur (*path diagram*)
* Menggambarkan hubungan antar-variabel dengan menggunakan diagram jalur
* Spesifikasi model dengan _syntax_ `lavaan` untuk spesifikasi model jalur di _module_ SEMLj
* Asumsi kausalitas (?) dan limitasi

::: {.callout-tip}
#### Menggambar diagram jalur
Untuk menggambar diagram jalur, peserta dapat menggunakan MS Power Point, Canva, atau _software_ lainnya yang serupa. Rekomendasi saya: gunakan [draw.io](https://app.diagrams.net/?src=about) yang merupakan _software open source_ dan sangat unggul untuk menggambar berbagai macam diagram, termasuk _flowchart_.
:::

### Bagian 4️⃣: _Confirmatory Factor Analysis_ (CFA)
* Definisi *factor analysis*
* *Exploratory* vs *confirmatory factor analysis*
* Kapan menggunakan CFA?
* [*Constraining parameter* model](https://psycnet.apa.org/record/2008-06808-005)
* Model pengukuran (paralel, *tau equivalence*, dan *congeneric*)
* Variabel indikator (reflektif vs formatif)
* *Correlated error variances*
* Metode estimasi
* Menuliskan hasil analisis CFA dalam laporan penelitian

::: {.callout-important}
#### Materi CFA tidak diajarkan
Karena keterbatasan waktu, bagian **_Confirmatory Factor Analysis_** **_tidak diajarkan_** di _workshop_, tetapi **harus dibaca cepat** oleh peserta terlebih dahulu sebelum sesi _workshop_. Materi tersedia di laman web ini dan dapat dipelajari secara mandiri.
:::

### Bagian 5️⃣: Dasar-dasar _Structural Equation Modeling_ (SEM)
* Dasar-Dasar SEM: Model struktural & pengukuran
* Tahapan *modeling* dengan menggunakan SEM
  * Spesifikasi model
  * Identifikasi model
  * Estimasi model
  * Menguji model
  * Memodifikasi model
* *Degree of freedom*
* *Underidentified*, *just-identified*, dan *overidentified model*
* Jenis-jenis kriteria untuk menilai ketepatan model (*model fit*)
  * [*Model fit*](http://www.ejbrm.com/issue/download.html?idArticle=183)
  * *Model comparison*/*Incremental fit indices*
  * *Model parsimony*
  * *Parameter fit*
* Menguji hipotesis
  * *Statistical power*
  * Ukuran sampel
* Membedakan antara pendekatan dua-langkah dengan empat-langkah *modeling* dengan SEM
* Menuliskan hasil analisis SEM dalam laporan penelitian

### Bagian 6️⃣: _Multigroup_ SEM (MG-SEM)
* Kapan perlu menggunakan MG-SEM?
* *Measurement invariance*
  * *Configural invariance*
  * *Weak/metric invariance*
  * *Strong/scalar invariance*
  * *Strict/residual invariance*
  * *Homogeneity of latent variable variances*
  * *Homogeneity of factor means*
* Mengevaluasi *measurement invariance*
* Menuliskan hasil analisis MG-SEM dalam laporan penelitian

::: {.callout-note}
#### Unduh materi dalam bentuk PDF 
Klik _navigation bar_ yang mengarah pada PDF materi, kemudian tekan `ctrl` dan `p` bersamaan. Setelah _window_ untuk _print_ muncul, pilih `Save to PDF` dan klik `Save`.
:::

## Referensi

* Baujean, A.A. (2014). *Latent Variable Modeling Using R: A step-by-step guide*. New York: Routledge.
* Galluci, M. (2025). SEMLj: A Suite for Structural Equation Models for jamovi (v1.2.5). <https://semlj.github.io/index.html>
* Schumacker, R.E. & Lomax, R.G. (2016). *A Beginner's Guide to Structural Equation Modeling (4th edition)*. New York: Routledge.
* Van De Schoot, R., Schmidt, P., De Beuckelaer, A., Lek, K., & Zondervan-Zwijnenburg, M. (2015). [Measurement invariance](https://www.frontiersin.org/articles/10.3389/fpsyg.2015.01064/full). _Frontiers in psychology, 6_, 1064.
* Putnick, D. L., & Bornstein, M. H. (2016). [Measurement invariance conventions and reporting: The state of the art and future directions for psychological research](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5145197/). _Developmental review, 41_, 71-90.

## Contoh penelitian dengan `MG-SEM`

* Rodriguez, V. J., Radusky, P. D., Kumar, M., Nemeroff, C. B., & Jones, D. (2018). [Measurement invariance of the Childhood Trauma Questionnaire by gender, poverty level, and HIV status](https://www.sciencedirect.com/science/article/abs/pii/S2468171718300085). _Personalized Medicine in Psychiatry, 11_, 16-22.
* Liu, Y., Millsap, R. E., West, S. G., Tein, J. Y., Tanaka, R., & Grimm, K. J. (2017). [Testing measurement invariance in longitudinal data with ordered-categorical measures](https://psycnet.apa.org/record/2016-25480-001). _Psychological methods, 22_(3), 486.
* Bowden, S. C., Saklofske, D. H., Van de Vijver, F. J. R., Sudarshan, N. J., & Eysenck, S. B. G. (2016). [Cross-cultural measurement invariance of the Eysenck Personality Questionnaire across 33 countries](https://www.sciencedirect.com/science/article/abs/pii/S0191886916302835). _Personality and Individual Differences, 103_, 53-60.
* Bieda, A., Hirschfeld, G., Schönfeld, P., Brailovskaia, J., Zhang, X. C., & Margraf, J. (2017). [Universal happiness? Cross-cultural measurement invariance of scales assessing positive mental health](http://www.kli.psy.ruhr-uni-bochum.de/klipsy/public/margraf%20Journals%20with%20Peer-Review/Bieda%20et%20al%202016%20Universal%20happiness.pdf). _Psychological assessment, 29_(4), 408.

## Sumber belajar lainnya

* [Learning Statistics with jamovi](https://www.learnstatswithjamovi.com/)
* [Video tutorial jamovi dari Datalab](https://datalab.cc/tools/jamovi)
* [Materi workshop SEM: Sacha Epskamp](http://sachaepskamp.com/workshop-materials/Psych_rstats_Club.zip)
* Cho, E. (2016). [Making Reliability Reliable: A Systematic approach to reliability coefficients](articles/cho2016.pdf). _Organizational Research Methods, 19_(4), 651-682.

## Sebelum mulai workshop

* Sebaiknya semua peserta sudah memasang jamovi pada perangkatnya masing-masing, untuk menghindari terlalu banyaknya waktu untuk menyelesaikan *troubleshooting* instalasi ketika *workshop*.
* Peserta sangat disarankan untuk menonton [video tutorial jamovi](https://datalab.cc/tools/jamovi) sebelum *workshop* untuk belajar menavigasikan menu dan fitur yang ada dalam jamovi. Cukup hanya dengan menonton bagian *Welcome*, *Installing jamovi*, dan *Navigating jamovi* (total durasi kurang lebih hanya 7 menit).

## Cara instalasi *module* SEMLj v1.2.5

Gunakan **jamovi versi stabil yang terbaru** (2.6.44) [untuk Windows](https://www.jamovi.org/downloads/jamovi-2.6.44.0-win-x64.exe) atau [MacOS](https://www.jamovi.org/download.html).

Mohon untuk menyimak video cara mengelola *modules* di jamovi berikut ini. Di video ini saya mencontohkan cara instalasi _module_ GAMLj. Instalasi _modules_ SEMj v1.2.5 mengikuti prosedur yang persis sama.

{{< video https://www.youtube.com/watch?v=XWavBKgTEuU >}}

## Tutorial jamovi + _modules_

Saat ini, sudah cukup banyak tutorial jamovi yang tersedia. Salah satu yang paling populer dan komperhensif adalah tutorial di bawah ini ⬇️

{{< video https://youtu.be/t0tQcs-E5Z4?si=wur9Er_M92zR-J2v >}}

[Simak seluruh video tutorial di <i class="fa-brands fa-youtube"></i> _playlist_.](https://www.youtube.com/playlist?list=PLvYqRUmlLZUMJ0EUxuTAA1f407wmBQ1QX)

## Evaluasi _workshop_

Setelah _workshop_, peserta dimohon untuk mengisi kuesioner evaluasi yang dapat diakses di _menu bar_ `Survei` bagian pojok kanan atas sebagai bahan evaluasi untuk meningkatkan kualitas materi _workshop_ di masa depan.